[workspace]
members = ["native/*"]

[profile.release]
lto = true
codegen-units = 1
debug = false

[patch."https://github.com/hhanh00/zcash-params.git"]
zcash_params = { path = "native/zcash-params" }
