name: Build and Release MacOS Universal

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build_mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: env
        run: |
          cat build.env >> $GITHUB_ENV
          echo $PWD/flutter/bin >> $GITHUB_PATH

      - name: build
        run: ./build-scripts/mac/build-mac.sh "$FLUTTER_VERSION"

      - name: codesign
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
          MACOS_CERTIFICATE_ID: ${{ secrets.MACOS_CERTIFICATE_ID }}
        run: ./build-scripts/mac/codesign-mac.sh "$MACOS_CERTIFICATE" "$MACOS_CERTIFICATE_PWD" "$MACOS_CI_KEYCHAIN_PWD" "$MACOS_CERTIFICATE_ID"

      - name: notarize
        env:
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
        run: ./build-scripts/mac/notarize-mac.sh "$MACOS_NOTARIZATION_APPLE_ID" "$MACOS_NOTARIZATION_TEAM_ID" "$MACOS_NOTARIZATION_PWD"

      - name: package
        run: ./build-scripts/mac/pkg-mac.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./ywallet-universal.dmg
