name: Build and Release Flatpak / Linux

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/Dockerfile-linux
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/zwallet_linux:latest"
          secrets: "pwd=${{ secrets.JKS_PASSWD }}"

      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: "${{ secrets.DOCKER_HUB_USERNAME }}/zwallet_linux:latest"
          path: '/root'
